In [ ]:
import pandas as pd

customers_df = pd.read_json("noahs-customers.jsonl", lines=True)
orders_df = pd.read_json("noahs-orders.jsonl", lines=True)
products_df = pd.read_json("noahs-products.jsonl", lines=True)

In [2]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8260 entries, 0 to 8259
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customerid    8260 non-null   int64
 1   name          8260 non-null   str
 2   address       8260 non-null   str
 3   citystatezip  8260 non-null   str
 4   birthdate     8260 non-null   str
 5   phone         8260 non-null   str
 6   timezone      8260 non-null   str
 7   lat           8260 non-null   float64
 8   long          8260 non-null   float64
dtypes: float64(2), int64(1), str(6)
memory usage: 580.9 KB

In [3]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 213232 entries, 0 to 213231
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   orderid     213232 non-null  int64
 1   customerid  213232 non-null  int64
 2   ordered     213232 non-null  str
 3   shipped     213232 non-null  str
 4   items       213232 non-null  object
 5   total       213232 non-null  float64
dtypes: float64(1), int64(2), object(1), str(2)
memory usage: 9.8+ MB

In [4]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1278 entries, 0 to 1277
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sku             1278 non-null   str
 1   desc            1278 non-null   str
 2   wholesale_cost  1278 non-null   float64
 3   dims_cm         1278 non-null   object
dtypes: float64(1), object(1), str(2)
memory usage: 40.1+ KB

In [5]:
customers_df.head()

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long
0,1001,Jacqueline Alvarez,105N Elizabeth St,"Manhattan, NY 10013",1958-01-23,315-377-5031,America/New_York,40.718170,-73.997468
1,1002,Julie Howell,185-1 Linden St,"Brooklyn, NY 11221",1956-12-03,680-537-8725,America/New_York,40.694261,-73.921665
2,1003,Christopher Ali,174-28 Baisley Blvd,"Jamaica, NY 11434",2001-09-20,315-846-6054,America/New_York,40.689022,-73.773475
3,1004,Christopher Rodriguez,102 Mount Hope Pl,"Bronx, NY 10453",1959-07-10,516-275-2292,America/New_York,40.849389,-73.909157
4,1005,Jeffrey Wilkinson,17 St Marks Pl,"Manhattan, NY 10003",1988-09-08,838-830-6960,America/New_York,40.728045,-73.987117

In [6]:
def phoneword_inv(s: str)->str:
    m = {
        'a': '2',
        'b': '2',
        'c': '2',
        'd': '3',
        'e': '3',
        'f': '3',
        'g': '4',
        'h': '4',
        'i': '4',
        'j': '5',
        'k': '5',
        'l': '5',
        'm': '6',
        'n': '6',
        'o': '6',
        'p': '7',
        'q': '7',
        'r': '7',
        's': '7',
        't': '8',
        'u': '8',
        'v': '8',
        'w': '9',
        'x': '9',
        'y': '9',
        'z': '9'
    }
    return ''.join(map(lambda c: m.get(c.lower(), ''), s))

In [7]:
customers_df['last_name_phoneword'] = customers_df['name'].str.split().map(lambda sl: phoneword_inv(sl[-1]))

In [14]:
customers_df[customers_df['phone'].str.replace('-', '') == customers_df['name'].str.split().map(lambda sl: phoneword_inv(sl[-1]))]

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long,last_name_phoneword
207,1208,Sam Tannenbaum,221 Banker St,"Brooklyn, NY 11222",1994-09-13,826-636-2286,America/New_York,40.7257,-73.9555,8266362286