In [ ]:
import pandas as pd

customers_df = pd.read_json("noahs-customers.jsonl", lines=True)
orders_df = pd.read_json("noahs-orders.jsonl", convert_dates=['ordered', 'shipped'], lines=True)
products_df = pd.read_json("noahs-products.jsonl", lines=True)

In [2]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8260 entries, 0 to 8259
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customerid    8260 non-null   int64
 1   name          8260 non-null   str
 2   address       8260 non-null   str
 3   citystatezip  8260 non-null   str
 4   birthdate     8260 non-null   str
 5   phone         8260 non-null   str
 6   timezone      8260 non-null   str
 7   lat           8260 non-null   float64
 8   long          8260 non-null   float64
dtypes: float64(2), int64(1), str(6)
memory usage: 580.9 KB

In [10]:
rabbit_years = [
  ["1951-02-06", "1952-01-27"],
  ["1963-01-25", "1964-02-13"],
  ["1975-02-11", "1976-01-31"],
  ["1987-01-29", "1988-02-17"],
  ["1999-02-16", "2000-02-05"]
]
def is_rabbit_year(s: str):
    return any(start <= s < end for start, end in rabbit_years)

def is_cancer_sign(s: str):
    m_d = s[-5:]  # Extract month and day (e.g., "02-06")
    return "06-21" <= m_d <= "07-22"

In [ ]:
customers_df[customers_df['phone'] == '332-274-4185'] # contractor

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long
474,1475,Joshua Peterson,100-75 148th St,"Jamaica, NY 11435",1947-02-05,332-274-4185,America/New_York,40.708951,-73.808561

In [15]:
customers_df[customers_df['birthdate'].map(is_rabbit_year) & customers_df['birthdate'].map(is_cancer_sign) & (customers_df['citystatezip'] == 'Jamaica, NY 11435')]

,customerid,name,address,citystatezip,birthdate,phone,timezone,lat,long
1549,2550,Robert Morton,145-51 107th Ave,"Jamaica, NY 11435",1999-07-08,917-288-9635,America/New_York,40.689595,-73.804871