In [1]:
import pandas as pd

customers_df = pd.read_json("noahs-customers.jsonl", lines=True)
orders_df = pd.read_json("noahs-orders.jsonl", convert_dates=['ordered', 'shipped'], lines=True)
products_df = pd.read_json("noahs-products.jsonl", lines=True)

SKU IDs:

- `PET` pets
- `COL` collectible
- `DLI` deli
- `BKY` bakery
- `HOM` household goods

In [2]:
norm_orders_df = orders_df.explode('items', ignore_index=True)
norm_orders_df = pd.concat([norm_orders_df.drop(columns=['items']), pd.json_normalize(norm_orders_df['items'])], axis=1)

In [3]:
df = norm_orders_df.join(
    customers_df.set_index('customerid'),
    on='customerid',
).join(products_df.set_index('sku'), on='sku')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 426541 entries, 0 to 426540
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   orderid         426541 non-null  int64
 1   customerid      426541 non-null  int64
 2   ordered         426541 non-null  datetime64[us]
 3   shipped         426541 non-null  datetime64[us]
 4   total           426541 non-null  float64
 5   sku             426541 non-null  str
 6   qty             426541 non-null  int64
 7   unit_price      426541 non-null  float64
 8   name            426541 non-null  str
 9   address         426541 non-null  str
 10  citystatezip    426541 non-null  str
 11  birthdate       426541 non-null  str
 12  phone           426541 non-null  str
 13  timezone        426541 non-null  str
 14  lat             426541 non-null  float64
 15  long            426541 non-null  float64
 16  desc            426541 non-null  str
 17  wholesale_cost  426541 non-null  float64
 18  dims_cm         426541 non-null  object
dtypes: datetime64[us](2), float64(5), int64(3), object(1), str(8)
memory usage: 61.8+ MB

In [11]:
df[df['sku'].str.contains('PET') & df['citystatezip'].str.contains('Staten Island')].groupby(['customerid', 'birthdate', 'phone'])["qty"].agg("sum").sort_values(ascending=False).reset_index()

     customerid   birthdate         phone  qty
0          3068  1967-06-21  631-507-6048  169
1          2345  1970-04-27  516-570-4577   24
2          4795  1973-01-05  929-294-9773   16
3          5288  1999-02-22  838-390-1549   15
4          2861  1998-09-02  718-486-5382   13
..          ...         ...           ...  ...
129        8725  1956-08-03  838-955-0155    1
130        9042  1992-12-14  914-963-8871    1
131        8995  2001-05-04  914-925-2334    1
132        9154  1973-06-10  917-540-0444    1
133        9153  1976-05-20  315-324-3699    1

[134 rows x 4 columns]

In [12]:
df[df['customerid'] == 3068]

,orderid,customerid,ordered,shipped,total,sku,qty,unit_price,name,address,citystatezip,birthdate,phone,timezone,lat,long,desc,wholesale_cost,dims_cm
43273,22850,3068,2017-09-06 17:27:03,2017-09-10 16:45:00,10.32,PET8589,8,1.29,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Gluten-free Senior Cat Food, Pumpkin & Pumpkin",1.06,"[13.5, 13.0, 1.0]"
103761,53204,3068,2018-07-09 16:47:24,2018-07-09 16:47:24,12.04,PET0808,7,1.72,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Chicken & Chicken",1.48,"[20.0, 12.4, 3.0]"
115803,59213,3068,2018-09-08 18:33:50,2018-09-10 17:30:00,10.08,PET5719,7,1.44,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Wet Senior Cat Food, Chicken & Chicken",1.13,"[11.2, 9.4, 8.4]"
119411,61033,3068,2018-09-27 12:14:30,2018-09-27 12:14:30,18.80,PET9849,10,1.88,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Gluten-free Senior Cat Food, Pumpkin & Pumpkin",1.65,"[17.5, 6.0, 4.5]"
125103,63848,3068,2018-10-25 14:51:20,2018-10-25 16:00:00,16.24,PET8448,7,2.32,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Gluten-free Senior Cat Food, Shrimp & Shrimp",1.68,"[16.9, 16.7, 11.3]"
142101,72252,3068,2019-01-17 17:07:53,2019-01-20 15:30:00,9.94,PET9367,7,1.42,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Dry Senior Cat Food, Pumpkin & Pumpkin",1.10,"[14.1, 2.3, 2.0]"
151713,77027,3068,2019-03-05 14:37:42,2019-03-05 14:37:42,18.30,PET9232,10,1.83,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Gluten-free Senior Cat Food, Duck & Duck",1.50,"[19.8, 16.6, 15.7]"
174923,88693,3068,2019-06-29 12:26:33,2019-06-29 16:45:00,12.96,PET0406,8,1.62,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Wet Senior Cat Food, Salmon & Salmon",1.17,"[10.3, 9.5, 4.1]"
206661,104641,3068,2019-12-05 14:00:53,2019-12-05 14:00:53,22.80,PET6966,10,2.28,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Turkey & Turkey",1.76,"[15.0, 5.3, 0.5]"
214917,108679,3068,2020-01-16 15:04:09,2020-01-16 17:30:00,12.72,PET2255,8,1.59,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Salmon & Salmon",1.41,"[14.8, 11.6, 0.1]"
230445,116424,3068,2020-04-03 09:35:16,2020-04-03 09:35:16,10.96,PET9602,8,1.37,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Dry Senior Cat Food, Salmon & Salmon",1.06,"[16.2, 13.5, 10.8]"
234231,118314,3068,2020-04-22 19:12:58,2020-04-22 19:12:58,12.60,PET0129,7,1.80,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Turkey & Turkey",1.41,"[19.6, 12.8, 0.30000000000000004]"
257248,129701,3068,2020-08-16 15:53:11,2020-08-16 16:15:00,13.84,PET6778,8,1.73,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Gluten-free Senior Cat Food, Turkey & Turkey",1.24,"[16.4, 12.6, 2.4]"
268154,135108,3068,2020-10-10 19:27:30,2020-10-17 15:30:00,17.28,PET2040,9,1.92,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,Senior Cat Food,1.48,"[17.9, 11.9, 9.0]"
326030,163934,3068,2021-07-28 12:14:28,2021-07-28 20:30:00,7.77,PET0019,7,1.11,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Dry Senior Cat Food, Tuna & Tuna",0.89,"[18.6, 8.7, 7.2]"
330248,166089,3068,2021-08-18 18:00:16,2021-08-25 17:45:00,11.20,PET6668,8,1.40,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Wet Senior Cat Food, Salmon & Salmon",1.11,"[16.4, 11.0, 2.1]"
352034,176914,3068,2021-12-06 12:53:59,2021-12-06 15:30:00,13.02,PET2873,7,1.86,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Beef & Beef",1.63,"[17.2, 0.9, 0.6000000000000001]"
355412,178646,3068,2021-12-23 12:37:43,2021-12-23 16:00:00,9.68,PET6668,8,1.21,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Wet Senior Cat Food, Salmon & Salmon",1.11,"[16.4, 11.0, 2.1]"
387807,194824,3068,2022-06-05 10:42:32,2022-06-05 12:30:00,11.70,PET2437,9,1.30,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Dry Senior Cat Food, Turkey & Turkey",0.93,"[17.6, 5.4, 2.7]"
397184,199511,3068,2022-07-22 09:26:24,2022-07-22 09:26:24,10.72,PET9692,8,1.34,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Wet Senior Cat Food, Duck & Duck",0.96,"[15.5, 11.4, 5.1]"
405751,203701,3068,2022-09-02 13:10:12,2022-09-02 20:30:00,15.12,PET1993,8,1.89,Nicole Wilson,208 Ramapo Ave,"Staten Island, NY 10309",1967-06-21,631-507-6048,America/New_York,40.539844,-74.20782,"Vegan Senior Cat Food, Shrimp & Shrimp",1.68,"[13.7, 10.4, 10.3]"