In [1]:
import pandas as pd

customers_df = pd.read_json("noahs-customers.jsonl", lines=True)
orders_df = pd.read_json("noahs-orders.jsonl", convert_dates=['ordered', 'shipped'], lines=True)
products_df = pd.read_json("noahs-products.jsonl", lines=True)

SKU IDs:

- `PET` pets
- `COL` collectible
- `DLI` deli
- `BKY` bakery
- `HOM` household goods

In [2]:
norm_orders_df = orders_df.explode('items', ignore_index=True)
norm_orders_df = pd.concat([norm_orders_df.drop(columns=['items']), pd.json_normalize(norm_orders_df['items'])], axis=1)

In [16]:
df = norm_orders_df.join(
    customers_df.set_index('customerid'),
    on='customerid',
).join(products_df.set_index('sku'), on='sku')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 426541 entries, 0 to 426540
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   orderid         426541 non-null  int64
 1   customerid      426541 non-null  int64
 2   ordered         426541 non-null  datetime64[us]
 3   shipped         426541 non-null  datetime64[us]
 4   total           426541 non-null  float64
 5   sku             426541 non-null  str
 6   qty             426541 non-null  int64
 7   unit_price      426541 non-null  float64
 8   name            426541 non-null  str
 9   address         426541 non-null  str
 10  citystatezip    426541 non-null  str
 11  birthdate       426541 non-null  str
 12  phone           426541 non-null  str
 13  timezone        426541 non-null  str
 14  lat             426541 non-null  float64
 15  long            426541 non-null  float64
 16  desc            426541 non-null  str
 17  wholesale_cost  426541 non-null  float64
 18  dims_cm         426541 non-null  object
dtypes: datetime64[us](2), float64(5), int64(3), object(1), str(8)
memory usage: 61.8+ MB

In [22]:
df[df['unit_price'] < df['wholesale_cost']].groupby(['customerid'])["qty"].agg("sum").sort_values(ascending=False).reset_index()

      customerid  qty
0           4167   55
1           2560    6
2           7792    6
3           3402    6
4           2610    6
...          ...  ...
1257        9165    1
1258        9173    1
1259        9191    1
1260        9219    1
1261        9121    1

[1262 rows x 2 columns]

In [23]:
df[df['customerid'] == 4167]

,orderid,customerid,ordered,shipped,total,sku,qty,unit_price,name,address,citystatezip,birthdate,phone,timezone,lat,long,desc,wholesale_cost,dims_cm
20360,11265,4167,2017-05-13 10:58:07,2017-05-13 15:00:00,9.11,TOY0481,1,9.11,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Automatic Board Game,15.64,"[10.4, 9.6, 1.8]"
29106,15650,4167,2017-06-26 19:48:36,2017-06-26 19:48:36,16.74,PET7145,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,"Wet Cat Food, Turkey & Turkey",1.06,"[18.0, 9.3, 9.1]"
29107,15650,4167,2017-06-26 19:48:36,2017-06-26 19:48:36,16.74,HOM2761,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Rug Cleaner,1.43,"[19.6, 11.7, 0.2]"
29108,15650,4167,2017-06-26 19:48:36,2017-06-26 19:48:36,16.74,TOY1479,1,11.79,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Star Wars Doll,22.55,"[14.2, 5.6, 3.4]"
29109,15650,4167,2017-06-26 19:48:36,2017-06-26 19:48:36,16.74,PET3443,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,"Gluten-free Senior Cat Food, Chicken & Chicken",1.45,"[18.5, 18.4, 2.5]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359568,180771,4167,2022-01-13 18:37:23,2022-01-13 18:37:23,13.62,TOY7389,1,13.62,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Star Wars Board Game,25.77,"[8.8, 8.2, 0.30000000000000004]"
367336,184612,4167,2022-02-21 10:06:09,2022-02-21 10:06:09,0.99,PET4284,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,"Wet Adult Cat Food, Beef & Beef",0.75,"[15.2, 14.0, 2.2]"
379378,190610,4167,2022-04-23 14:25:36,2022-04-23 18:45:00,3.05,COL7663,1,2.06,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Noah's Poster (white),4.07,"[5.6, 4.8, 4.1]"
379379,190610,4167,2022-04-23 14:25:36,2022-04-23 18:45:00,3.05,PET2899,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,"Dry Cat Food, Duck & Duck",1.14,"[18.7, 12.0, 0.30000000000000004]"
398802,200309,4167,2022-07-30 08:56:06,2022-07-30 13:00:00,0.99,DLI6168,1,0.99,Sherri Long,2092 Seward Ave,"Bronx, NY 10473",1975-04-09,585-838-9161,America/New_York,40.818198,-73.86752,Salted Cucumber Salad,1.03,"[19.2, 12.3, 1.6]"