In [1]:
import pandas as pd

customers_df = pd.read_json("noahs-customers.jsonl", lines=True)
orders_df = pd.read_json("noahs-orders.jsonl", convert_dates=['ordered', 'shipped'], lines=True)
products_df = pd.read_json("noahs-products.jsonl", lines=True)

SKU IDs:

- `PET` pets
- `COL` collectible
- `DLI` deli
- `BKY` bakery
- `HOM` household goods

In [2]:
norm_orders_df = orders_df.explode('items', ignore_index=True)
norm_orders_df = pd.concat([norm_orders_df.drop(columns=['items']), pd.json_normalize(norm_orders_df['items'])], axis=1)

In [3]:
df = norm_orders_df.join(
    customers_df.set_index('customerid'),
    on='customerid',
).join(products_df.set_index('sku'), on='sku')

In [4]:
products_df[products_df['sku'].str.contains('COL')]

,sku,desc,wholesale_cost,dims_cm
5,COL0037,Noah's Jewelry (green),28.32,"[17.4, 11.2, 5.7]"
6,COL0041,Noah's Ark Model (HO Scale),2487.35,"[7.2, 4.3, 0.4]"
8,COL0065,Noah's Jewelry (mauve),33.52,"[19.0, 12.2, 10.5]"
21,COL0166,Noah's Action Figure (blue),13.98,"[12.1, 7.7, 7.2]"
22,COL0167,Noah's Bobblehead (blue),5.36,"[8.9, 5.6, 0.6000000000000001]"
...,...,...,...,...
1191,COL9349,Noah's Action Figure (orange),15.47,"[16.6, 12.9, 11.9]"
1202,COL9420,Noah's Jewelry (amber),30.01,"[13.8, 9.1, 4.9]"
1246,COL9773,Noah's Poster (magenta),4.13,"[7.2, 4.9, 1.9]"
1253,COL9819,Noah's Lunchbox (blue),9.87,"[14.2, 4.1, 3.3]"
1268,COL9948,Noah's Jewelry (magenta),32.97,"[18.0, 17.5, 6.2]"

In [12]:
df[df['sku'].str.contains('COL')][['customerid', 'sku']].drop_duplicates().groupby('customerid')['sku'].agg("count").sort_values(ascending=False)

customerid
3808    85
4254    31
8665    30
3914    30
6855    30
        ..
3570     1
3569     1
9078     1
9073     1
9184     1
Name: sku, Length: 3290, dtype: int64

In [13]:
df[df['customerid'] == 3808]

,orderid,customerid,ordered,shipped,total,sku,qty,unit_price,name,address,citystatezip,birthdate,phone,timezone,lat,long,desc,wholesale_cost,dims_cm
32,1015,3808,2017-01-31 10:29:22,2017-01-31 15:15:00,13.48,COL8357,1,13.48,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Noah's Lunchbox (mauve),9.21,"[19.9, 17.4, 9.8]"
370,1184,3808,2017-02-01 22:19:28,2017-02-07 13:00:00,13.81,COL6858,1,13.81,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Noah's Jersey (blue),10.60,"[16.0, 6.6, 4.0]"
584,1295,3808,2017-02-02 23:25:54,2017-02-04 09:30:00,11.78,COL6461,1,11.78,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Noah's Jersey (white),9.36,"[18.8, 3.8, 1.3]"
768,1381,3808,2017-02-03 17:56:15,2017-02-05 10:30:00,3.87,COL7866,1,3.87,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Noah's Gift Box (white),3.06,"[8.8, 7.4, 5.9]"
840,1416,3808,2017-02-04 01:06:07,2017-02-04 12:30:00,3.89,COL7036,1,3.89,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Noah's Gift Box (red),3.04,"[18.5, 15.7, 6.3]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412177,206967,3808,2022-10-04 18:14:34,2022-10-05 19:00:00,6.29,DLI6192,1,1.35,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Salted Cabbage Sandwich,1.13,"[4.0, 1.6, 1.5]"
425143,213533,3808,2022-12-10 00:01:58,2022-12-10 17:15:00,5.75,BKY5319,1,1.47,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Raspberry Mandelbrot,1.09,"[12.6, 12.1, 2.8]"
425144,213533,3808,2022-12-10 00:01:58,2022-12-10 17:15:00,5.75,TOY9241,1,1.45,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,Mechanical Fidget Toy,1.10,"[14.5, 12.0, 1.3]"
425145,213533,3808,2022-12-10 00:01:58,2022-12-10 17:15:00,5.75,PET5897,1,1.25,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,"Dry Cat Food, Beef & Beef",0.99,"[14.7, 8.9, 0.5]"
425146,213533,3808,2022-12-10 00:01:58,2022-12-10 17:15:00,5.75,PET5402,1,1.58,James Smith,132 Spring St,"Manhattan, NY 10012",1953-12-10,212-547-3518,America/New_York,40.724902,-74.00252,"Vegan Senior Cat Food, Pumpkin & Pumpkin",1.29,"[19.5, 15.0, 2.7]"